CREATE DATABASE StudentDb;

CREATE TABLE Students
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  FullName VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Age INT NOT NULL,
  City VARCHAR(100),
  CreatedAt DATETIME DEFAULT GETDATE()
)

CREATE TABLE Courses
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  CourseName VARCHAR(100) NOT NULL,
  CourseTeacher VARCHAR(100) NOT NULL,
  Fee Money NOT NULL
)

CREATE TABLE StudentCourses
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  StudentId INT FOREIGN KEY REFERENCES Students(Id),
  CourseId INT FOREIGN KEY REFERENCES Courses(Id)
)